version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: nestjs-typeorm-graphql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

  web:
    depends_on:
      - db
    build: .
    ports:
      - '8090:8090'
    expose:
      - '8090'

# Names our volume
volumes:
  db_data: {}
